application:
  yml:
server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: bison-oauth2-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost.nacos:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost.redis
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"
