server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: bison-system
  cloud:
    nacos:
      discovery:
        server-addr: localhost.nacos:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
